name: Snakemake dry-run

on:
  push:
  pull_request:

jobs:
  dryrun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Snakemake
        run: |
          python -m pip install --upgrade pip
          pip install snakemake==8.*

      - name: Prepare minimal manifest (if missing)
        run: |
          mkdir -p data/manifests config
          if [ ! -f data/manifests/run_20190401.tsv ]; then
            cat > data/manifests/run_20190401.tsv <<'TSV'
sample_id	organism	isolate_origin	barcode_id	biosample_accession	pico_green_ng_per_uL	pool_included	comments
OMZ823	Treponema denticola	dental_plaque	NB01	SAMN11253855	150.77	yes	—
TSV
          fi

      - name: Snakemake dry-run
        run: |
          snakemake -n --directory .