# ===================================================================
# ||         CONFIGURATION FOR BACTERIAL ASSEMBLY PIPELINE         ||
# ===================================================================
# This file controls the behavior of the entire Snakemake workflow.
# Edit the values below to match your project's needs.

# -------------------------------------------------------------------
# 1. INPUT DATA CONFIGURATION
# -------------------------------------------------------------------
# The pipeline discovers samples from a TSV (Tab-Separated Values) file.
# This is the most scalable way to manage one or hundreds of samples.
samples_sheet: "config/samples.tsv"


# -------------------------------------------------------------------
# 2. RESOURCE AND REFERENCE PATHS
# -------------------------------------------------------------------
# Central location for all external reference files and databases.

resources:
  # Path to the reference genome for evaluation with QUAST.
  reference_genome: "resources/references/ecoli_k12_mg1655.fasta"

  # Path where the Bakta database will be stored.
  # The pipeline will automatically download it to this location if it's not found.
  # You do NOT need to run `bakta_db download` yourself.
  bakta_db: "resources/bakta_db"


# -------------------------------------------------------------------
# 3. TOOL-SPECIFIC PARAMETERS
# -------------------------------------------------------------------
# Fine-tune the parameters for each major step in the pipeline.

filtering:
  # If true, reads will be filtered by length and quality.
  enabled: true
  min_length: 1000
  # Discard the worst 5% of reads, keeping the best 95%.
  keep_percent: 95

assembly:
  # Estimated genome size for the assembler (e.g., "4.6m", "2.8k").
  # This is a crucial parameter for Flye.
  genome_size: "4.6m"

polishing:
  # Medaka model to use for polishing. This must match your basecaller and flowcell.
  # Find available models with `medaka model list`.
  # Common examples: r1041_e82_400bps_sup_g615, r941_min_high_g360
  medaka_model: "r1041_e82_400bps_sup_g615"

annotation:
  # Choose the annotation tool. Options: "prokka" or "bakta".
  # The pipeline will run the selected tool.
  tool: "bakta"


# -------------------------------------------------------------------
# 4. GLOBAL THREAD & RESOURCE DEFAULTS
# -------------------------------------------------------------------
# Default number of threads to use for each program.
# These can be overridden for specific rules in the Snakefile if needed.

threads:
  filtlong: 4
  flye: 8
  minimap2: 8
  racon: 8
  medaka: 8
  quast: 4
  prokka: 8
  bakta: 8