# ================================================================= #
#                         RULE: REPORTING                           #
# ================================================================= #
# This rule aggregates all QC and evaluation results into a single MultiQC report.

rule multiqc:
    input:
        # We create a single list of all dependencies by concatenating the
        # lists generated by each expand() call. This is the correct syntax.
        expand("results/{sample}/qc/nanoplot/NanoPlot-report.html", sample=ONT_SAMPLES) +
        expand("results/{sample}/qc/fastqc", sample=ILLUMINA_SAMPLES) +
        expand("results/{sample}/evaluation/quast/", sample=ASSEMBLY_SAMPLES) + 
        # Add the MOB-suite output directories as a dependency.
        # This ensures that MOB-suite runs before MultiQC is generated.
        # The conditional check ensures this only runs if plasmid detection is enabled.
        (expand("results/{sample}/plasmid/mob_suite/", sample=ASSEMBLY_SAMPLES) if config["tools"]["plasmid_detection"]["enabled"] else [])
    output:
        "results/multiqc_report.html"
    log:
        "logs/multiqc.log"
    conda:
        "../envs/report.yaml" # Assumed path
    params:
        title="Multi-sample Genome Assembly QC Report"
    shell:
        # The '.' tells MultiQC to scan the entire project directory from the top.
        # It will automatically find all the relevant files from the input list and more.
        # --force overwrites previous reports.
        "multiqc . --filename {output} --title \"{params.title}\" --force &> {log} 2>&1"