# File: workflow/envs/base.yaml
name: np-asm
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core
  - python =3.11
  - snakemake >=8,<9
  - pip

  # General CLI utils (safe to have here)
  - pandas
  - pyyaml
  - click
  - rich
  - tqdm
  - requests
  - biopython

  # Optional: used by fetch scripts / potential rules
  - pigz
  - curl
  - wget

  # For plotting/HTML reports if needed
  - jinja2
  - matplotlib
  - seaborn

  # Ensure reproducible solves
  - pip:
      # pin dorado CLI via pip only if needed later (commented by default)
      # - dorado==0.4.3
      - tabulate